In [1]:
import numpy as np
from numpy.random import default_rng
from numpy import linalg as LA
# https://numpy.org/doc/stable/user/basics.creation.html
# https://numpy.org/doc/stable/reference/routines.linalg.html
import sympy as sp 
# https://docs.sympy.org/latest/tutorials/intro-tutorial/matrices.html
from scipy import linalg as sLA
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html#scipy.linalg.eig
x,y,r,t=sp.symbols('x,y,r,t')

# Creating Arrays

## 1d arrays

In [2]:
np.array([1,2,3,4]) # Manual 1d array

array([1, 2, 3, 4])

In [3]:
np.arange(1,5) # 1d array with consecutive terms

array([1, 2, 3, 4])

In [4]:
np.arange(7,45,10) # From 7 upto, but not exceeding, 45 by 10s

array([ 7, 17, 27, 37])

In [5]:
np.linspace(7, 37, 11) # From 7 to 45 with 11 evenly spaced entries

array([ 7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.])

## 2d arrays

In [6]:
np.array([
    [1,2,3,4],
    [5,6,7,8]
]) # Manual 2d array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
np.diag([1, 2, 3]) # 3x3 with diagonal entries

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [8]:
np.eye(3,dtype=int) # 3x3 "identity" array with integer entries

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
np.eye(3,5,dtype=int) # 3x5 "identity" array with integer entries

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [10]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
np.zeros((2,3)) # 2x3 zero matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,2)) # 3x4 ones matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
default_rng(42).random((3,3)) # A random array, 42 is the seed for the random number generator

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

# Manipulating Arrays

In [14]:
I=np.eye(3)

In [15]:
A=np.array([
    [2,0,1],
    [0,1,2],
    [0,0,3]
])

In [16]:
B=np.zeros((2,3))

In [17]:
C=np.ones((2,3))

In [18]:
np.block([
    [A,I],
    [B,C]
]) # Array defined in blocks

array([[2., 0., 1., 1., 0., 0.],
       [0., 1., 2., 0., 1., 0.],
       [0., 0., 3., 0., 0., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [20]:
np.concatenate((A,B),axis=0)

array([[2., 0., 1.],
       [0., 1., 2.],
       [0., 0., 3.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array([
    A[0],
    B[1],
    C[2]
]) # Array built from rows of other arrays

array([[2., 0., 1.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [ ]:
np.array([A[1],I[0],A[0]]) # Array built from rows of other arrays

array([[0., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.]])

In [ ]:
A[0] # Row 0

array([2, 0, 1])

In [ ]:
A[:,0] # Column 0

array([2, 0, 0])

In [ ]:
2*A[1:2]+1 # 2*Second row of A plus 1

array([[1, 3, 5]])

In [ ]:
print(A[:2]+1) # First two rows of A with 1 added to them, but is actually a new array
A

[[3 1 2]
 [1 2 3]]


array([[2, 0, 1],
       [0, 1, 2],
       [0, 0, 3]])

In [ ]:
A[:2]

array([[2, 0, 1],
       [0, 1, 2]])

In [ ]:
r,c=np.shape(A[:2])

In [ ]:
r

2

In [ ]:
Bc=B.copy() # Make a copy of B
Bc

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Bc[:,1]=A[:,0] # Replace one column with another
Bc

array([[0., 2., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.column_stack((A[:,0],I[:,2]))

array([[2., 0.],
       [0., 0.],
       [0., 1.]])

In [ ]:
np.transpose(A)

array([[2, 0, 0],
       [0, 1, 0],
       [1, 2, 3]])

# Some Basic Matrix Stuff

In [ ]:
M=1/2*np.array([
    [3,2,1],
    [0,2,0],
    [1,0,7]
],dtype=int)

In [ ]:
LA.det(A) # Determinant of A

6.0

In [ ]:
A.max()

3

In [ ]:
A.min()

0

In [ ]:
A.sum()

9

In [ ]:
v=np.array([1/3,1/3,1/3]) # A vector v

In [ ]:
v

array([0.33333333, 0.33333333, 0.33333333])

In [ ]:
np.shape(np.transpose(v))

(3,)

In [ ]:
A+v

array([[2.33333333, 0.33333333, 1.33333333],
       [0.33333333, 1.33333333, 2.33333333],
       [0.33333333, 0.33333333, 3.33333333]])

In [ ]:
np.matmul(A,v)

array([1., 1., 1.])

In [ ]:
np.outer(A[0],v)

array([[0.66666667, 0.66666667, 0.66666667],
       [0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333]])

In [ ]:
np.inner(A[0],v)

1.0

In [ ]:
v.transpose()@A[0]

1.0

In [ ]:
vi=v
for i in range(5): # Iteratively multiplying v by M
    print(vi)
    vi=M@vi

[0.33333333 0.33333333 0.33333333]
[1.         0.33333333 1.33333333]
[2.5        0.33333333 5.16666667]
[ 6.66666667  0.33333333 19.33333333]
[20.          0.33333333 71.        ]


In [ ]:
LA.norm(A) # The norm of M

4.358898943540674

In [ ]:
np.trace(A) # The trace of M

6

In [ ]:
sol_vec=LA.solve(M,v) # Solving an equation of the form ax=b

In [ ]:
M@sol_vec

array([0.33333333, 0.33333333, 0.33333333])

In [ ]:
A_inv=LA.inv(A)
A_inv

array([[ 0.5       ,  0.        , -0.16666667],
       [ 0.        ,  1.        , -0.66666667],
       [ 0.        ,  0.        ,  0.33333333]])

In [ ]:
M@LA.inv(M)

array([[ 1.00000000e+00, -4.85722573e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 5.55111512e-17, -5.55111512e-17,  1.00000000e+00]])

In [ ]:
LA.inv(M)@M

array([[1.00000000e+00, 0.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

# Eigen-Stuff and Diagonalization

In [ ]:
A=np.array([[2,0,1],[0,1,2],[0,0,3]])

In [ ]:
A

array([[2, 0, 1],
       [0, 1, 2],
       [0, 0, 3]])

In [ ]:
eig_val, eig_vec = LA.eig(A) # Eigenvalues and Eigen Vectors of A

In [ ]:
eig_val # Array of eignevalues

array([2., 1., 3.])

In [ ]:
P=eig_vec # Matrix with eigenvectors as columns
print(P[:,1]==A@P[:,1])
print(A@P[:,2]==3*P[:,2])
P

[ True  True  True]
[ True  True  True]


array([[1.        , 0.        , 0.57735027],
       [0.        , 1.        , 0.57735027],
       [0.        , 0.        , 0.57735027]])

In [ ]:
A@P

array([[2.        , 0.        , 1.73205081],
       [0.        , 1.        , 1.73205081],
       [0.        , 0.        , 1.73205081]])

In [ ]:
D=np.diag(eig_val) # Diagonal matrix with eig_val
D

array([[2., 0., 0.],
       [0., 1., 0.],
       [0., 0., 3.]])

In [ ]:
P_inv=LA.inv(P) # The inverse of a matrix
P_inv

array([[ 1.        ,  0.        , -1.        ],
       [ 0.        ,  1.        , -1.        ],
       [ 0.        ,  0.        ,  1.73205081]])

In [ ]:
np.matmul(np.matmul(P,D),P_inv)==A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
D_Temp=P_inv@(A@P)
D_Temp==D

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# With Some Sympy

In [ ]:
spA=sp.Matrix(A)
spA

Matrix([
[2, 0, 1],
[0, 1, 2],
[0, 0, 3]])

In [ ]:
spA.det()

6

In [ ]:
LA.det(A)

6.0

In [ ]:
spA.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [ ]:
sp.Matrix(np.column_stack((A,A[:,2]))).rref()[0]

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 1]])

In [ ]:
np.matmul(A,spA)

array([[4, 0, 5],
       [0, 1, 8],
       [0, 0, 9]], dtype=object)

In [ ]:
type(A)

numpy.ndarray

In [ ]:
type(spA)

sympy.matrices.dense.MutableDenseMatrix

In [ ]:
type(A@spA)

sympy.matrices.dense.MutableDenseMatrix

In [ ]:
type(np.matmul(A,spA))

numpy.ndarray

In [ ]:
np.array(spA.tolist())==A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.array(spA[:,0].tolist())

array([[2],
       [0],
       [0]], dtype=object)

In [ ]:
A[:,0]

array([2, 0, 0])

In [ ]:
[x,y,t]@np.matmul(A,[x,y,t])

3*t**2 + x*(t + 2*x) + y*(2*t + y)